name: Cross-Platform Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Run weekly to ensure continued compatibility
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight on Sunday

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust 1.83.0
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.83.0
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Build
        run: cargo build --verbose
      
      - name: Run tests
        run: cargo test --verbose

  # Test with minimum supported Rust version
  msrv:
    name: Test with minimum supported Rust version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install minimum supported Rust version
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0  # Minimum supported Rust version
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Build with minimum supported Rust version
        run: cargo build --verbose
      
      - name: Test with minimum supported Rust version
        run: cargo test --verbose