name: Security Audit

on:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight on Sunday
  workflow_dispatch:  # Allow manual triggering

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust 1.83.0
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.83.0
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
      
      - name: Run security audit
        run: cargo audit